<a href="https://colab.research.google.com/github/joaossmacedo/SoccerAnalysis/blob/main/notebooks/analysis/player_specific/2025_06_25_gk_generic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [1]:
# !python3 -m pip install soccerdata
# import soccerdata as sd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
import pandas as pd
pd.set_option('display.max_columns', 100)

# Params

In [3]:
path_shots = '/content/drive/My Drive/database/soccerdata/fbref/raw_clean/shot_events/database.csv'
path_player_matches = '/content/drive/My Drive/database/soccerdata/fbref/raw_clean/player_match_stats/summary/database.csv'

In [4]:
# player_name = 'Mike Maignan'
# player_name = 'Đorđe Petrović'
player_name = 'Alisson'
# player_name = 'Jan Oblak'
# player_name = 'Jordan Pickford'
# player_name = 'Ederson'
# player_name = 'Gianluigi Donnarumma'
# player_name = 'Yann Sommer'
# player_name = 'Marc-André ter Stegen'
# player_name = 'David de Gea'
# player_name = 'Thibaut Courtois'
# player_name = 'Lucas Chevalier'
# player_name = 'Manuel Neuer'
# player_name = 'Keylor Navas'

season = [
  f'{i}{i+1}' for i in range(17, 25)
]

# Code

## Prepare Colab

In [5]:
from google.colab import drive
import os

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Getting data

In [6]:
df_shots = pd.read_csv(path_shots)
df_shots.head(2)

,league,season,game,minute,player,team,xG,PSxG,outcome,distance,body_part,notes,SCA 1_player,SCA 1_event,SCA 2_player,SCA 2_event,is_volley,is_freekick,is_deflected,game_date,game_team_h,game_team_a
0,ENG-Premier League,1718,2017-08-11 Arsenal-Leicester City,2,Alexandre Lacazette,Arsenal,0.06,0.37,Goal,13,Head,NaN,Mohamed Elneny,Pass (Live),Héctor Bellerín,Pass (Live),0,0,0,2017-08-11,Arsenal,Leicester City
1,ENG-Premier League,1718,2017-08-11 Arsenal-Leicester City,4,Riyad Mahrez,Leicester City,0.08,NaN,Off Target,17,Left Foot,NaN,NaN,NaN,NaN,NaN,0,0,0,2017-08-11,Arsenal,Leicester City

In [7]:
df_player_matches = pd.read_csv(path_player_matches)
df_player_matches.head(2)

,league,season,game,team,player,jersey_number,nation,age,min,Performance_Gls,Performance_Ast,Performance_PK,Performance_PKatt,Performance_Sh,Performance_SoT,Performance_CrdY,Performance_CrdR,Performance_Touches,Performance_Tkl,Performance_Int,Performance_Blocks,Expected_xG,Expected_npxG,Expected_xAG,SCA_SCA,SCA_GCA,Passes_Cmp,Passes_Att,Passes_Cmp%,Passes_PrgP,Carries_Carries,Carries_PrgC,Take-Ons_Att,Take-Ons_Succ,game_id,pos_GK,pos_DF,pos_CB,pos_RB,pos_LB,pos_WB,pos_DM,pos_CM,pos_MF,pos_LW,pos_LM,pos_AM,pos_RM,pos_RW,pos_FW,game_date,game_team_h,game_team_a
0,ENG-Premier League,1718,2017-08-11 Arsenal-Leicester City,Arsenal,Aaron Ramsey,8,WAL,26-228,24.0,1,0,0,0,4,1,0,0,19.0,0.0,0,0.0,0.4,0.4,0.0,1.0,0.0,9.0,12.0,75.0,1.0,13.0,0.0,0.0,0.0,e3c3ddf0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,2017-08-11,Arsenal,Leicester City
1,ENG-Premier League,1718,2017-08-11 Arsenal-Leicester City,Arsenal,Alex Oxlade-Chamberlain,15,ENG,23-361,90.0,0,0,0,0,6,2,0,0,84.0,3.0,3,1.0,0.2,0.2,0.1,4.0,0.0,48.0,67.0,71.6,6.0,54.0,9.0,9.0,8.0,e3c3ddf0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,2017-08-11,Arsenal,Leicester City

## Cleaning data

In [8]:
df_shots = df_shots[~df_shots['player'].str.endswith('(pen)')]
df_shots['goal'] = (df_shots['outcome'] == 'Goal').astype('int')
df_shots['PSxG'] = df_shots['PSxG'].fillna(0)
df_shots.head(1)

/tmp/ipython-input-8-3479065225.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_shots['goal'] = (df_shots['outcome'] == 'Goal').astype('int')
/tmp/ipython-input-8-3479065225.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_shots['PSxG'] = df_shots['PSxG'].fillna(0)

,league,season,game,minute,player,team,xG,PSxG,outcome,distance,body_part,notes,SCA 1_player,SCA 1_event,SCA 2_player,SCA 2_event,is_volley,is_freekick,is_deflected,game_date,game_team_h,game_team_a,goal
0,ENG-Premier League,1718,2017-08-11 Arsenal-Leicester City,2,Alexandre Lacazette,Arsenal,0.06,0.37,Goal,13,Head,NaN,Mohamed Elneny,Pass (Live),Héctor Bellerín,Pass (Live),0,0,0,2017-08-11,Arsenal,Leicester City,1

## Filtering games

In [9]:
if player_name is not None:
  df_player_matches = df_player_matches[df_player_matches['player'] == player_name]
  print(len(df_player_matches))
if season is not None:
  df_player_matches = df_player_matches[df_player_matches['season'].astype('str').isin(season)]
  print(len(df_player_matches))
df_player_matches = df_player_matches[df_player_matches['min'] >= 90]
print(len(df_player_matches))
len(df_player_matches)

263
263
260

260

In [10]:
df_player_matches.head(1)

,league,season,game,team,player,jersey_number,nation,age,min,Performance_Gls,Performance_Ast,Performance_PK,Performance_PKatt,Performance_Sh,Performance_SoT,Performance_CrdY,Performance_CrdR,Performance_Touches,Performance_Tkl,Performance_Int,Performance_Blocks,Expected_xG,Expected_npxG,Expected_xAG,SCA_SCA,SCA_GCA,Passes_Cmp,Passes_Att,Passes_Cmp%,Passes_PrgP,Carries_Carries,Carries_PrgC,Take-Ons_Att,Take-Ons_Succ,game_id,pos_GK,pos_DF,pos_CB,pos_RB,pos_LB,pos_WB,pos_DM,pos_CM,pos_MF,pos_LW,pos_LM,pos_AM,pos_RM,pos_RW,pos_FW,game_date,game_team_h,game_team_a
40103,ITA-Serie A,1718,2017-08-20 Atalanta-Roma,Roma,Alisson,1,BRA,24-322,90.0,0,0,0,0,0,0,0,0,34.0,0.0,0,0.0,0.0,0.0,0.0,1.0,0.0,24.0,34.0,70.6,0.0,16.0,0.0,1.0,1.0,634f9715,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2017-08-20,Atalanta,Roma

## Filtering shots faced

In [11]:
df_player_matches = df_player_matches[['game', 'team']]
df_player_matches.columns = ['game', 'team_player']

df_player_shots = df_shots.merge(
  df_player_matches, on=['game'], how='inner'
)
df_player_shots = df_player_shots[df_player_shots['team'] != df_player_shots['team_player']]
print(len(df_player_shots))
df_player_shots.head(1)

2934

,league,season,game,minute,player,team,xG,PSxG,outcome,distance,body_part,notes,SCA 1_player,SCA 1_event,SCA 2_player,SCA 2_event,is_volley,is_freekick,is_deflected,game_date,game_team_h,game_team_a,goal,team_player
0,ITA-Serie A,1718,2017-08-20 Atalanta-Roma,4,Papu Gómez,Atalanta,0.04,0.04,Saved,20,Right Foot,NaN,Papu Gómez,Take-On,NaN,NaN,0,0,0,2017-08-20,Atalanta,Roma,0,Roma

## Grouping data

In [12]:
print(player_name)

PSxG = sum(df_player_shots['PSxG'])
goals = sum(df_player_shots['goal'])
ratio = -1 * ((goals / PSxG) - 1)

print(f'PSxG: {PSxG}')
print(f'goals: {goals}')
print(f'% goals saved: {ratio:.2%}')

Alisson
PSxG: 308.16999999999956
goals: 273
% goals saved: 11.41%

## Look at performance per difficulty

In [13]:
df_player_shots_faced = df_player_shots[df_player_shots['outcome'].isin(['Saved', 'Goal'])]
print(len(df_player_shots_faced))
df_player_shots_faced['PSxG_cat'] = pd.cut(df_player_shots_faced['PSxG'], [0, 0.1, 0.2, 0.5, 1], labels=['0.00-0.10', '0.10-0.20', '0.20-0.50', '0.50-1.00'])

1088

/tmp/ipython-input-13-221259484.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_player_shots_faced['PSxG_cat'] = pd.cut(df_player_shots_faced['PSxG'], [0, 0.1, 0.2, 0.5, 1], labels=['0.00-0.10', '0.10-0.20', '0.20-0.50', '0.50-1.00'])

In [14]:
df_player_shots_faced['count'] = 0
df_grouped = df_player_shots_faced.groupby('PSxG_cat',observed=True).agg({'count': 'count', 'goal': 'sum', 'PSxG': 'sum'})
df_grouped['% goals saved'] = -1 * ((df_grouped['goal'] / df_grouped['PSxG']) - 1)
df_grouped['% goals saved']

print(player_name)
df_grouped

Alisson

/tmp/ipython-input-14-933777565.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_player_shots_faced['count'] = 0

           count  goal    PSxG  % goals saved
PSxG_cat
0.00-0.10    405    23   20.94      -0.098376
0.10-0.20    168    28   25.52      -0.097179
0.20-0.50    297    82   97.14       0.155858
0.50-1.00    217   139  164.57       0.155375